/**
 * Java. Level 2. Lesson 8
 * Simple server for chat (Простой сервер для чата)
 *
 * @author Sergey Iryupin
 * @version 0.2.2 dated Jan 19, 2018
 * Rus comments by Dmitriy Grishin
 */

import java.io.*;
import java.net.*;
import java.sql.*;
import java.util.*;//для работы со ссылочными массивами


public class SimpleServer implements IConstants{
    //константы берутся из интерфейса IConstants

    //Модернизация:
    List<ClientHandler> clients;//объявляем ссылочный массив (список) для хранения объектов обработки клиентов

    public static void main(String[] args) {
        new SimpleServer();
    }

    SimpleServer() {
        System.out.println(SERVER_START);//сообщение в консоль, что клиент подключился
        clients = new ArrayList<>();//инициализируем ссылочный массив

        //В ресурсах try() создаём сокет сервера (ServerSocket is AutoCloseable)
        try (ServerSocket server = new ServerSocket(SERVER_PORT)) {
            //бесконечный цикл создания нитей обработки новых клиентов
            while (true) {
                Socket socket = server.accept();//ожидание подключения клиента и получения ссылки на клиентский сокет
                System.out.println("#" + (clients.size() + 1) + CLIENT_JOINED);//сообщение в консоль сервера, какой клиент подключился

                ClientHandler client = new ClientHandler(socket);//создаём объект обработки клиента
                clients.add(client); //добавляем объект в ссылочный массив клиентов

                new Thread(client).start();//стартуем нить обработки отдельного клиента
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        System.out.println(SERVER_STOP);
    }

    //Метод проверки авторизации клиента:
    /**
     * checkAuthentication: check login and password
     * Параметры:
     * @param  login for checking
     * @param  passwd for checking
     * Возвращает boolean в зависимости от успешности авторизации
     * @return if the pair login/passwd is found in the database,
     *         authentication is successful
     */
    private boolean checkAuthentication(String login, String passwd) {
        boolean result = false;
        try {
            // loads a class, including running its static initializers (загружаем класс драйвера)
            Class.forName(DRIVER_NAME);
            // connect db (соединяемся с БД)
            Connection connect = DriverManager.getConnection(SQLITE_DB);
            // looking for login && passwd in db (поиск соответствия в БД)
            PreparedStatement pstmt = connect.prepareStatement(SQL_SELECT);//SQL_SELECT = "SELECT * FROM users WHERE login=?"
            // replace "?" to the login (замена "?" на "login", переданный в метод checkAuthentication в качестве параметра)
            pstmt.setString(1, login);
            // returns ResultSet object generated by the query
            ResultSet rs = pstmt.executeQuery();
            // process rows from the query result
            while (rs.next())
                //Получить строку колонки PASSWD_COL и проверить на равенство значению "passwd",
                //переданному в метод checkAuthentication в качестве параметра:
                result = rs.getString(PASSWD_COL).equals(passwd);
            // close all
            rs.close();
            pstmt.close();
            connect.close();
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            return false;
        }
        return result;
    }

    //Метод для отправки сообщений всем клиентам:
    private void broadcastMsg(String msg){
        for (ClientHandler client: clients)
            client.sendMsg(msg);
    }

    /**
     * ClientHandler: (ВНУТРЕННИЙ класс для нити обработки отдельного клиента)
     */
    class ClientHandler implements Runnable {
        BufferedReader reader;
        public PrintWriter writer;
        Socket socket;//для запоминания клиентского сокета
        String name;//имя подключённого клиента

        //В конструктор передаём параметр - ссылку на клиентский сокет
        ClientHandler(Socket clientSocket) {
            try {
                socket = clientSocket;
                reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));//читатель входящего потока
                writer = new PrintWriter(socket.getOutputStream());//писатель исходящего потока
                name = "Client #" + (clients.size() + 1);//задаём начальное имя клиенту
            } catch(Exception ex) {
                System.out.println(ex.getMessage());
            }
        }

        //Метод, отправляющий сообщение:
        void sendMsg(String msg) {
            try{
                writer.println(msg);
                writer.flush();
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }

        @Override
        public void run() {
            String message;
            try {
                do {
                    message = reader.readLine();//читаем сообщение от клиента
                    if (message != null) {
                        System.out.println(name + ": " + message);//выводим его в консоль

                        //Если сообщение начинается с АУТЕНТИФИКАЦИОННОГО слова:
                        if (message.startsWith(AUTH_SIGN)) {
                            String[] wds = message.split(" ");
                            //применяем метод проверки авторизации
                            if(checkAuthentication(wds[1],wds[2])) {
                                name = wds[1];//даём имя клиенту по логину
                                sendMsg("Hello, " + name);
                                sendMsg("\0");//пустой символ для печати символа-подсказки у клиента
                            } else {
                                System.out.println(name + ": " + AUTH_FAIL);//"Authentication failure." - отказ в аутентификации
                                writer.println(AUTH_FAIL);//Отправка этого же сообщения клиенту
                                message = EXIT_COMMAND;//присваиваем значение exit, чтобы корректно выйти из нити этого клиента
                            }
                        //Иначе если ДРУГОЕ сообщение и оно не команда exit:
                        } else if (!message.equalsIgnoreCase(EXIT_COMMAND)) {
                            broadcastMsg(name + ": " + message);//отправляем ВСЕМ клиентам
                            broadcastMsg("\0");//пустой символ для печати символа-подсказки у клиента
                        }
                    }
                } while (!message.equalsIgnoreCase(EXIT_COMMAND));//пока сообщение не равно команде exit
                
                clients.remove(this);//для удаления нити обработки вышедшего клиента из ссылочного массива клиентов
                socket.close();//закрытие клиентского сокета
                System.out.println(name + CLIENT_DISCONNECTED);
            } catch(Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }
}
